route:
    receiver: 'slack'

receivers:
    - name: 'slack'
      slack_configs:
          - send_resolved: true
            title: "{{.CommonAnnotations.summary}}"
            text: "{{.CommonAnnotations.description}}"
            username: 'Prometheus'
            channel: 'hosted_eteq'
            api_url: 'https://hooks.slack.com/services/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'
