global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'eteq-monitoring'

rule_files:
  - "swarm_node.rules.yml"
  - "swarm_task.rules.yml"

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'traefik'
    scrape_interval: 5s
    static_configs:
      - targets: ['traefik:8080']

  - job_name: 'haproxy'
    scrape_interval: 5s
    static_configs:
      - targets: ['haproxy-exporter:9101']

  - job_name: 'postgres'
    scrape_interval: 5s
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'cadvisor'
    dns_sd_configs:
    - names:
      - 'tasks.cadvisor'
      type: 'A'
      port: 8080

  - job_name: 'node'
    scrape_interval: 5s
    dns_sd_configs:
    - names:
      - 'tasks.node-exporter'
      type: 'A'
      port: 9100
    static_configs:
      - targets: ['10.0.1.141:9100','10.0.1.142:9100','10.0.1.143:9100','10.0.1.144:9100','10.0.1.146:9100']


